### ISSUE TITLE
Decide on Tech Stack

### ISSUE THREAD

**Issue by louisefindlay23** [louisefindlay23/recTV-web#1]
Decide on a tech stack for the web app.

**Comment by louisefindlay23** [comment]
- WanjaMike knows React and Next.js.
- I know Vanilla JS, EJS and a bit of Vue.

So it makes sense to make some sort of Node.js web app which I assume is compatible with K8. We also need to decide how to call our chosen APIs (#2 and #3), either through a wrapper library or something like axios.

**Comment by louisefindlay23** [comment]
Any particular preferences on the technologies we use, @WanjaMIKE?

**Comment by WanjaMIKE** [comment]
We settled on Vue. I will try to catch along since I was more on NextJS. Its a good thing you already have the app's basic structure

**Comment by louisefindlay23** [comment]
Thanks, @WanjaMIKE. It's vanilla JS plus EJS (simple templating for passing data to the front-end).
