### ISSUE TITLE
Decide on a TV Metadata & Recommendation API

### ISSUE THREAD

**Issue by louisefindlay23** [louisefindlay23/recTV-web#3]
Decide on an API for TV Show metadata (Shows and Films?) and (positive) recommendations. They could be one and the same or two separate APIs.

**Options**
TMDB
TVDB
IMDB
OMDB

**Comment by louisefindlay23** [comment]
TVDB has gone paid so that's out.

Both Trakt and TMDB have recommendations but Trakt's requires the user to have an account so TMDB API may be simpler for the end user.

Fanart.tv API is quite basic so the OMDB API might be best for TV Show artwork (unless we just want to use what we can retrieve from our Recommendations API)

**Overall:** TMDB API looks the best for our use case. Would just need to look into wrappers for our chosen tech stack or Axios etc. to call it

What do you think, @WanjaMIKE?

**Comment by WanjaMIKE** [comment]
I have used OMDP before but am flexible @louisefindlay23

**Comment by louisefindlay23** [comment]
Awesome. I've used it in the past as well but it didn't seem to do the Recommendations part so went with TVDB. Using Axios because the wrappers don't seem to work with all the endpoints we need.
